site_name: Documentación de ContaPortable
site_url: https://contaportabledesarrollo03.github.io/CPDOCS
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: orange
      accent: blue
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: blue
      accent: orange
  features:
    - navigation.footer
  icon: 
    repo: fontawesome/brands/gitkraken

  logo: "assets/logo.png"
  favicon: "assets/favicon.png"

repo_url: https://github.com/YECAPP/CPDOCS
repo_name: Documentación de ContaPortable

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- attr_list
- md_in_html
- pymdownx.blocks.caption
- pymdownx.keys # Para dibujar teclas

- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - glightbox
  - search

extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com/contaportable
    - icon: simple/facebook
      link: https://facebook.com/contaportable

copyright: Copyright &copy; 2025 ContaPortable - Yuri Ernesto Calderón Rodríguez